texts = {
    "uz": {
        "start": "Salom! Tilni tanlang:",
        "chosen": "Siz o'zbek tilini tanladingiz!",
        "name": "Ismingiz nima?",
        "age": "Necha yoshdasiz?",
        "sex": "Jinsingizni tanlang:",
        "phone": "Telefon raqamingizni yuboring:",
        "done": "Ro'yxatdan o'tdingiz ✅",
        "name2": "Ismingiz nima?",
        "gender": "Jinsingizni tanlang:",
        "before": "18 dan yoshroq",
        "empty":"⚠️ Eksport uchun ma'lumotlar mavjud emas.",
        "error":"⚠️ Xato: promouter ro'yxatdan o'tmagan.",
        "finish":"✅ Rahmat! So'rov yakunlandi.",
        "q1": "Hozir birinchi bo'lib qaysi sut/sut mahsulotlari brendini eslaysiz?",
        "q2": "Bugun qaysi brendni sotib olishni rejalashtiryapsiz?",
        "q3": "Agar sizning brendingiz bo'lmasa, qaysi brendni tanlaysiz?",
        "q4": "Qaysi brendni tavsiya qilasiz?",
        "q5": "Qaysi kompaniyaning sutini afzal ko'rasiz?",
        "q6":"So'nggi 3 oy ichida qaysi sut mahsulotlari reklamasini ko'rdingiz?",
        "q7":"Iltimos, ushbu reklamani aynan qayerda korganingizni ayta olasizmi?",
        "q8":"Yana qanday sut/sut mahsulotlari brendlarini eslay olasiz?",
        "q9":"Quyidagi logotiplarning qaysi birlarini bilasiz?",
        "q10":"Pure Milky ni yaqinlaringiz va tanishlaringizga tavsiya qilasizmi?",
        "write":"✍️ Sut mahsuloti brendingizni kiriting:",
        "res1":"Kamida bitta variantni tanlang!",
        "type":"Brendni qo'lda kiriting:",
        "req11":"📋 So'rovni boshlash?",
        "other":"Boshqa",
        "unknown":"Eslay olmayman",

    },
    "ru": {
        "unknown":"Не помню",
        "other":"Другое",
        "req11":"📋 Начать опрос?",
        "type":"Введите марку вручную:",
        "res1":"Выберите хотя бы один вариант!",
        "write":"✍️ Введите свой вариант молочного продукта:",
        "finish":"✅ Спасибо! Опрос завершён.",
        "error":"⚠️ Ошибка: промоутер не зарегистрирован.",
        "empty":"⚠️ Нет данных для экспорта.",
        "q1": "Какую марку молочные продукции вы сейчас ПЕРВОЙ вспомнили?",
        "q2": "Какую из этих марок вы СЕГОДНЯ планируете купить?",
        "q3": "Если вашей марки не окажется, какую возьмёте взамен?",
        "q4": "Какой бренд вы бы порекомендовали?",
        "q5": "Молоко какой компании вы предпочитаете?",
        "q6":"Рекламу какой молочной продукции вы видели за последние 3 месяца",
        "q7":"Можете рассказать, где именно вы видели эту рекламу?",
        "q8":"Можете ещё какие-нибудь марки молочный продукции вспомнить?",
        "q9":"Какие из этих логотипов вы знаете?",
        "q10":"Порекомендовали бы близким и знакомым Pure Milky",
        "before": "До 18",
        "start": "Привет! Выберите язык:",
        "chosen": "Вы выбрали русский!",
        "name": "Как вас зовут?",
        "age": "Сколько вам лет?",
        "sex": "Выберите пол:",
        "phone": "Отправьте ваш номер телефона:",
        "done": "Регистрация завершена ✅",
        "name2": "Как вас зовут?",
        "gender": "Выберите пол:",
    }
}
